- name: installing nginx
  hosts: local
  become: yes
  connection: local
  tasks:
  - name: installing nginx tasks
    ansible.builtin.package:
      name: nginx
      state: present
    when: state == "disabled"