- name: variables from files
  hosts: local
  connection: local
  vars_files:
    testdata.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"