- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: name
    prompt: pls enter name
    enabled: false
  - name: password
    prompt: pls enter password
  tasks:
  - name: print from prompt
    ansible.builtin.debug:
      msg: "Hello  {{ name }},  password {{ password }}" 