- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: name1
    prompt: pls enter name
    private: false
  - name: password
    prompt: pls enter password
  tasks:
  - name: print from prompt
    ansible.builtin.debug:
      msg: "Hello  {{ name1 }},  password {{ password }}" 